# Site settings
title: Atlantico Yoga Jeckyll Version
email: your-email@domain.com
description: Yoga, Bray, Atlantico Yoga, yoga classes
baseurl: "/atlanticoyoga" # the subpath of your site, e.g. /blog/
url: "http://mpbarral.github.io/" # the base hostname & protocol for your site


#User settings
username: Maria Perez
github_username:  mpbarral
# Build settings
markdown: kramdown
theme: Twenty-Jekyll-Theme
